import { useState } from 'react';
import { api } from '../lib/api';
import Icon from './DriveIcon';
const label={administrator:'Studio administrator',manager:'Project manager',editor:'Editor',owner:'Project owner',recipient:'Recipient'};
export function AccessBadge({status}){return <span className={`d-status ${status||'pending'}`}><span/>{status||'pending'}</span>}
export default function ProjectSharing({project:p,busy,run}){
 const perm=p.access.permissions,base=`/projects/${p.id}`;
 const active=p.member_access.filter(m=>m.role==='recipient'&&m.approval!=='revoked');
 const [second,setSecond]=useState(active[0]?.email||''),[third,setThird]=useState(active[1]?.email||''),[error,setError]=useState('');
 async function submit(e){e.preventDefault();const emails=[p.owner_email,second,third].map(s=>(s||'').trim().toLowerCase()).filter(Boolean);if(emails.length<2){setError('Add at least one other email address.');return}if(new Set(emails).size!==emails.length){setError('Each recipient must have a different email address.');return}setError('');await run(()=>api(`${base}/members`,{method:'PUT',body:{emails}}));}
 return <div className="d-sharing"><p className="d-muted">Access is specific to this project. Email verification and studio approval are separate.</p><h3>People with access</h3><div className="d-people">{p.member_access.map(m=><div className="d-person" key={m.email}><span className="d-avatar">{m.email[0].toUpperCase()}</span><div className="d-person-info"><strong>{m.email}</strong><span>{label[m.role]} · {m.verified_at?'Email verified':'Email not verified yet'}</span><AccessBadge status={m.approval}/></div>{perm.approve&&(m.role==='recipient'||perm.staff)&&<select aria-label={`Approval for ${m.email}`} value={m.approval} disabled={busy} onChange={e=>run(()=>api(`${base}/access`,{method:'PATCH',body:{email:m.email,approval:e.target.value}}))}><option value="pending" disabled>Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="revoked">Revoked</option></select>}</div>)}</div>
 {perm.recipients&&<form onSubmit={submit} className="d-form"><h3>Request recipient access</h3><p className="d-muted">Use 2–3 different emails, including your own. New recipients need studio approval.</p><label>Your verified owner email<input value={p.owner_email} readOnly/></label><label>Second recipient<input type="email" required autoComplete="off" value={second} onChange={e=>setSecond(e.target.value)}/></label><label>Third recipient <small>(optional)</small><input type="email" autoComplete="off" value={third} onChange={e=>setThird(e.target.value)}/></label>{error&&<p className="d-error" role="alert">{error}</p>}<button className="d-primary" disabled={busy}>Save recipient requests</button></form>}
 {perm.staff&&<form className="d-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,body=Object.fromEntries(new FormData(form));run(async()=>{await api(`${base}/staff`,{method:'PUT',body});form.reset()})}}><h3>Assign studio staff</h3><div className="d-form-row"><label>Staff email<input name="email" type="email" required/></label><label>Project role<select name="role"><option value="editor">Editor</option><option value="manager">Project manager</option></select></label></div><button disabled={busy} className="d-secondary">Assign to project</button></form>}
 <div className="d-restricted"><Icon name="lock"/><div><strong>Restricted project link</strong><p>Only approved people who verify their email can open project files.</p></div></div>
 {perm.consent&&<div className="d-consent"><h3>Public portfolio permission</h3><label><input type="checkbox" checked={p.public_consent} disabled={busy} onChange={e=>run(()=>api(`${base}/privacy`,{method:'PUT',body:{public_consent:e.target.checked}}))}/> I allow the studio to publish selected photos and videos.</label><p className="d-muted">You can withdraw permission here. Downloaded copies cannot be recalled.</p></div>}
 </div>
}
